services:
  api:
    build:
      context: .
      target: dev
    container_name: api
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    environment:
      - APP_ENV=local
      - DB_PORT=5432
      - DB_DATABASE=db
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
      - REDIS_CLIENT=predis
    depends_on:
      - redis-queue
    networks:
      - db
      - default

  nginx-server:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  queue-worker:
    build:
      context: .
      target: dev
    container_name: queue-worker
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=db
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_CLIENT=predis
      - QUEUE_CONNECTION=redis
      - ACTIVITY_LOGGER_ENABLED=false
    volumes:
      - ./:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    depends_on:
      - redis-queue
    networks:
      - db
      - default

  redis-queue:
    image: redis:7-alpine
    container_name: redis-queue
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data

networks:
  db:
    external: true
